/**
 * The Interface for the Fuzzbot plugin/extension. 
 */ 
#include "nsISupports.idl"

[scriptable, function, uuid(f5ebc90b-56b5-4bce-96c9-d2962c2af7f6)]
interface fuzzbotJSTripleHandlerCallback : nsISupports {
  boolean call(in string subject, in string predicate, in string object);
};

[scriptable, uuid(f5ebc90b-56b5-4bce-96c9-d2962c2af7f5)]
interface nsIFuzzbotExtension : nsISupports {
  long processRdfaTriples(
    in string uri, in string html,
    in fuzzbotJSTripleHandlerCallback callback);
   
  long tidyAndProcessRdfaTriples(
    in string uri, in string html,
    in fuzzbotJSTripleHandlerCallback callback);
};
