/**
 * The Interface for the Fuzzbot plugin/extension. 
 */ 
#include "nsISupports.idl"

[scriptable, uuid(f5ebc90b-56b5-4bce-96c9-d2962c2af7f5)]
interface nsIFuzzbotExtension : nsISupports {
  boolean processRdfaTriples(in string uri, in string html);
};
